name: Milestone Changelog
description: Re-generates changelog for given milestone
inputs:
  milestone:
    description: Milestone object containing number and title
    required: true
  token:
    description: Github token
    required: true
runs:
  using: "composite"
  steps:
    # The gh utility has a shortcut to filter merged PRs by milestone, while it would require
    # multiple calls in JS rest client
    - name: Find Merged Pull Requsts
      id: merged_milestone
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        milestone="$(jq -r '.title' <<< '${{ inputs.milestone }}')"
        prs="$(gh pr list \
          --repo ${{ github.repository }} \
          --search "milestone:${milestone}" \
          --state merged \
          --json number,url,title,body,state,milestone)"
        echo "::set-output name=prs::${prs}"

    - name: Collect Changelog
      id: changelog
      uses: shvgn/changelog@main
      with:
        token: ${{ inputs.token }}
        pull_requests: ${{ steps.merged_milestone.outputs.prs }}

    - name: Write Changelog File
      id: file
      shell: bash
      run: |
        mkdir -p ./CHANGELOG
        milestone="$(jq -r '.title' <<< '${{ inputs.milestone }}')"
        filename="./CHANGELOG/CHANGELOG-${milestone}.yml"
        cat > "$filename" <<EOBODYINACTION
        ${{ steps.changelog.outputs.yaml }}
        EOBODYINACTION

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3.10.1
      with:
        commit-message: Re-generate changelog
        title: Changelog ${{ inputs.milestone.title }}
        body: ${{ steps.changelog.outputs.markdown }}
        labels: changelog, auto
        base: main
        branch: changelog/${{ inputs.milestone.title }}
        token: ${{ inputs.token }} # questionable
        milestone: ${{ inputs.milestone.number }}
        delete-branch: true
