name: Milestone Changelog
description: Re-generates changelog for given milestone
inputs:
  milestone_title:
    description: Milestone title
    required: true
  milestone_number:
    description: Milestone number
    required: true
  token:
    description: Github token
    required: true
runs:
  using: "composite"
  steps:
    # The gh utility has a shortcut to filter merged PRs by milestone, while it would require
    # multiple calls in JS rest client
    - name: Find Merged Pull Requsts
      id: merged_milestone
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        prs="$(gh pr list \
          --repo '${{ github.repository }}' \
          --search 'milestone:${{ inputs.milestone_title }}' \
          --state merged \
          --json number,url,title,body,state,milestone)"
        echo "::set-output name=prs::${prs}"

    - name: Collect Changelog
      id: changelog
      uses: shvgn/changelog@main
      with:
        token: ${{ inputs.token }}
        pull_requests: ${{ steps.merged_milestone.outputs.prs }}

    - name: Write Changelog File
      id: file
      shell: bash
      run: |
        mkdir -p ./CHANGELOG
        filename='./CHANGELOG/CHANGELOG-${{ inputs.milestone_title }}.yml'
        cat > "$filename" <<EOBODYINACTION
        ${{ steps.changelog.outputs.yaml }}
        EOBODYINACTION

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3.10.1
      with:
        commit-message: Re-generate changelog
        base: main
        branch: changelog/${{ inputs.milestone_title }}
        milestone: ${{ inputs.milestone_number }}
        title: Changelog ${{ inputs.milestone_title }}
        body: ${{ steps.changelog.outputs.markdown }}
        labels: changelog, auto
        token: ${{ inputs.token }}
        delete-branch: true
