# Glossary
#   - MCPR = Milestone Changelog Pull Request, the result of this workflow
#
# Test cases
#   - Open milestone assigned to merged PR should add the PR to the MCPR
#   - Open milestone deassigned to merged PR should clean the PR to the MCPR
#   - Open milestone changed in merged PR should add the PR to new MCPR and remove it from old MCPR
#   - When the body of a merged PR is edited, MCPR body updates
#   - When PR changelog section is not formed or not valid, MCPR changelog contains a generic-form
#     entry for it
#   - When open milestone changes title, MCPR updates its title and body
#   - Closed milestone assigned to merged PR should not do anything
#   - Closed milestone deassigned to merged PR should not do anything
#   - Closed milestone changed in merged PR should add the PR to new MCPR and remove it from old MCPR
#   - When closed milestone changes title, nothing should change
#   - Any human action triggers the workflow only once
#
# Tasks
#   - Create board card for the changelog PR in 'In Progress' column?
#   - Close milestone when MCPR merge?
#   - Validate milestone title for semver before doing anything?

name: Changelog
on:
  push:
    branches:
      - "main"
  milestone:
    types:
      - "opened"
      - "edited"
  pull_request:
    types:
      - "closed"
      - "edited"
    branches:
      - "main"
  # A PR is an issue, and PR milestones are acceptable via the isseus API
  issues:
    types:
      - "milestoned"
      - "demilestoned"
# TODO permissions
# permissions:
#   pull-requests: write
jobs:
  milestones:
    name: Open milestones
    runs-on: ubuntu-latest
    steps:
      - name: Find Open Milestones
        id: milestones
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          milestones="$(gh api 'repos/${{ github.repository }}/milestones' \
            -q '[.[] | select(.state == "open") ]')"

          count="$(echo $milestones | jq '. | length')"

          echo "::set-output name=list::${milestones}"
          echo "::set-output name=count::${count}"

    outputs:
      list: ${{ steps.milestones.outputs.list }}
      count: ${{ steps.milestones.outputs.count }}

  chanegelogs:
    if: needs.milestones.outputs.count > 0
    name: Changelog ${{ matrix.milestone.title }}
    runs-on: ubuntu-latest
    needs:
      - milestones
    strategy:
      matrix:
        milestone: ${{ fromJSON( needs.milestones.outputs.list ) }}
        # token: [secrets.GITHUB_TOKEN]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create changelog
        uses: ./.github/actions/milestone-changelog
        with:
          milestone: ${{ toJSON( matrix.milestone ) }}
          token: ${{ secrets.GITHUB_TOKEN }}
