name: Milestone Changelog Generation
on:
  workflow_dispatch:
    inputs:
      milestone_title:
        description: Milestone title
        required: true

      milestone_number:
        description: Milestone number
        required: true

jobs:
  milestone_chanegelog:
    name: Milestone Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Upgrade changelog
        uses: ./.github/actions/milestone-changelog
        with:
          milestone_title: ${{ inputs.milestone_title }}
          milestone_number: ${{ inputs.milestone_number }}
          token: ${{ secrets.GITHUB_TOKEN }}
