name: changelog-command
on:
  repository_dispatch:
    types: [changelog-command]
jobs:
  changelog:
    name: Milestone Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          cat <<EOFINACTION
          ${{ toJSON( github.event.client_payload ) }}
          EOFINACTION

      - name: Checkout
        uses: actions/checkout@v2

      - name: Upgrade changelog
        uses: ./.github/actions/milestone-changelog
        with:
          milestone: ${{ toJSON( github.event.client_payload.pull_request.milestone ) }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add reaction for success
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray
