name: Changelog Command Dispatch
on:
  issue_comment:
    types: [created]
jobs:
  changelog-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Find milestone
        id: milestone
        uses: actions/github-script@v5
        with:
          result-encoding: json
          script: |
            const { status, data: issue } = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            if (status != 200) {
              core.warning(`GET issue error: status ${status}`)
              return
            }

            console.log("issue", issue)

            if (!issue.pull_request || !issue.milestone) {
              console.log(
                "condition not met",
                JSON.stringify({
                  pull_request: issue.pull_request,
                  milestone: issue.milestone
                })
              )
              return
            }

            console.log(JSON.stringify(issue.milestone))
            return issue.milestone

      - name: Slash Command Dispatch
        if: steps.milestone.outputs.result
        uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commands: |
            changelog
          dispatch-type: workflow
          static-args: |
            milestone=${{ toJSON( steps.milestone.outputs.result ) }}
