name: Upgrade Release Changelog
on:
  workflow_dispatch:
    inputs:
      comment-id:
        description: 'The comment-id of the slash command'
        required: true

jobs:
  chanegelog:
    name: Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Find milestone
       run:
        go gh api 'repos/shvgn/deckhouse/issues/9'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Create changelog
        uses: ./.github/actions/milestone-changelog
        with:
          milestone: ${{ toJSON( matrix.milestone ) }}
          token: ${{ secrets.GITHUB_TOKEN }}
