name: Changelog Command Dispatch
on:
  issue_comment:
    types: [created]
jobs:
  dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Dump
        run: |
          echo "EVENT CONTEXT"
          cat <<EOFINACTION
          ${{ github.event }}
          EOFINACTION

      - name: Checkout
        if: github.event.issue.pull_request && github.event.issue.pull_request.milestone.state == 'open' && contains(github.event.pull_request.labels.*.name, 'changelog')
        uses: actions/checkout@v2

      - name: Find milestone
        id: milestone
        uses: actions/github-script@v5
        with:
          result-encoding: json
          script: |
            const validate = require('./.github/scripts/changelog-command-validate.js')
            return await validate({ github, core, context })

      - name: Slash Command Dispatch
        if: steps.milestone.outputs.result
        uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{ secrets.CHANGELOG_ACCESS_TOKEN }}
          commands: changelog
          dispatch-type: repository
          issue-type: pull-request
